# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('activity', models.CharField(choices=[('-- please select --', '- Please Select -'), ('movie night', 'Movie Night'), ('laser tag', 'Laser Tag'), ('get lit', 'Get Lit')], max_length=255)),
                ('package', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('description', models.TextField(default='None')),
                ('snack', models.CharField(choices=[('-- please select --', '- Please Select -'), ('pizzas', 'Pizzas'), ('chips', 'Chips'), ('ice cream', 'Ice Cream'), ('donuts', 'Donuts'), ('candies', 'Candies'), ('cookies', 'Cookies'), ('hot dogs', 'Hot Dogs'), ('hamburgers', 'Hamburgers')], default='Not Shown', max_length=255)),
                ('drink', models.CharField(choices=[('-- please select --', '- Please Select -'), ('coca cola', 'Coca Cola'), ('dr. pepper', 'Dr. Pepper'), ('pepsi', 'Pepsi'), ('fanta', 'Fanta'), ('sprite', 'Sprite'), ('apple juice', 'Apple Juice'), ('capri sun', 'Capri Sun')], default='Not Shown', max_length=255)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartyPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snack', models.CharField(choices=[('-- please select --', '- Please Select -'), ('pizzas', 'Pizzas'), ('chips', 'Chips'), ('ice cream', 'Ice Cream'), ('donuts', 'Donuts'), ('candies', 'Candies'), ('cookies', 'Cookies'), ('hot dogs', 'Hot Dogs'), ('hamburgers', 'Hamburgers')], max_length=255)),
            ],
        ),
    ]
